package com.leafy.plantmanagementservice.model;

import com.leafy.common.model.BaseModel;
import com.leafy.plantmanagementservice.model.EmbeddedPlanEvent;
import lombok.*;
import lombok.experimental.FieldDefaults;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.FieldType;
import org.springframework.data.mongodb.core.mapping.MongoId;

import java.util.List;

/**
 * MongoDB document representing a disease treatment plan template generated by the RAG service.
 *
 * <p>A Plan is a <strong>reusable template/definition</strong> containing diagnosis information,
 * treatment metadata, and a schedule blueprint (embedded template events). Each concrete application
 * of a plan to a specific target (plant/farm/zone) is tracked by a separate {@link PlanApply} document.
 *
 * <p>Template events are stored as an embedded {@link EmbeddedPlanEvent} array in {@link #events}.
 * When a plan is applied, the consumer copies each entry into a real {@link PlantEvent} document.
 *
 * <p>Field names mirror the RAG service {@code Plan} Pydantic model so that data can flow from
 * the AI pipeline to the calendar with zero field mapping.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "plans")
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Plan extends BaseModel {

    @MongoId(FieldType.OBJECT_ID)
    String id;

    // ── Source tracking ───────────────────────────────────────────────────────

    /** ID of the user who triggered the plan via the RAG chat endpoint. */
    String userId;

    /** Profile ID of whoever created this plan (farmer or expert). */
    @Indexed
    String creatorId;

    /** Profile ID of the farmer who owns the target farm/plant. */
    @Indexed
    String ownerId;

    /**
     * {@code planId} UUID from the RAG service {@code PlanDoc}.
     * Allows the AI service to later look up which Java plan corresponds to its record.
     */
    String ragPlanId;

    /** Original natural-language question the user sent to the RAG service. */
    String question;

    /** Evidence source used by the AI plan generator: websearch or documents. */
    String source;

    // ── Diagnosis ─────────────────────────────────────────────────────────────

    /** Custom name for the plan */
    String planName;

    /** Full name of the identified disease, e.g. "Coffee Leaf Rust (Hemileia vastatrix)". */
    String diseaseName;

    /** LLM confidence in this diagnosis (0.0 = uncertain, 1.0 = certain). */
    Double confidenceScore;

    /** Severity: {@code LOW}, {@code MEDIUM}, or {@code HIGH}. */
    String severityLevel;

    /** Time sensitivity: {@code IMMEDIATE}, {@code HIGH}, or {@code NORMAL}. */
    String urgency;

    // ── Plan metadata ─────────────────────────────────────────────────────────

    /** All tools, materials, and chemicals needed to execute the full plan. */
    List<String> requiredInputs;

    /** Critical safety notes applicable to the whole plan (PPE, PHI, disposal). */
    List<String> safetyWarnings;

    /** Visual or measurable signs that the treatment is working. */
    String successIndicators;

    /** Estimated total cost for the entire plan (chemicals, tools, labour). */
    String estimatedCost;

    // ── Template events (blueprint schedule — embedded) ──────────────────────

    /**
     * Ordered list of template events embedded directly in this plan document.
     * These are the blueprint events that will be copied into real {@link PlantEvent}
     * documents for each {@link PlanApply} target.
     */
    List<EmbeddedPlanEvent> events;

    // ── Visibility ────────────────────────────────────────────────────────────

    /**
     * Whether this plan is publicly visible to all authenticated users.
     * When {@code false} (default), only the owner and creator can access it.
     */
    @Builder.Default
    boolean isPublic = false;

    /**
     * {@code true} when the plan was created by an expert on behalf of a farmer
     * (i.e. {@link #creatorId} differs from {@link #ownerId}).
     */
    @Builder.Default
    boolean isConsulted = false;
}
